config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    root :to => "static_pages#home"
    get 'food' => "static_pages#food"
    get 'history' => "static_pages#blog"
    resources :posts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
   
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
   
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:title, :body, :author, :img_url)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def food
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navigation">
    <ul class="header">
      <li><%= link_to t('.home_link'), root_path %></li>
      <li><%= link_to t('.food_link'), food_path %></li>
      <li><%= link_to t('.history_link'), history_path %></li>
      <li><%= link_to t('.dynamic_blog_link'), posts_path %></li>
    </ul>
  </nav>

  <div class="wrapper">
    <div class="container">
      <%= yield %>
    </div>
    <footer>
      <p><%= t('.language_options') %></p>
      <ul>
        <li><%= link_to 'English', :locale => :en %></li>
        <li><%= link_to '日本語', :locale => :jp %></li>
        <li><%= link_to '中文', :locale => :zh_CN %></li>
        <li><%= link_to 'Deutsch', :locale => :de %></li>
        <!-- You add links to veiw the page in new locales here-->
      </ul>
    </footer>
  </div>

</body>
</html>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/index.html.erb
<% if (@posts.count != 0) %>
   
  <% @posts.each do |post| %>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <figure>
      <%= image_tag post.img_url, width: "800px" %>
    </figure>
    <p class="credits"><%= post.author %> <span class="float-right"><%= post.created_at%></span></p>
    <p>
      <%= post.body %>
    </p>
  <% end %>

<% else %>

  <h1 class="NoPost"><%= t( 'posts.index.NoPost') %></h1>
  
  <img class="img1" src="http://wallpapers111.com/wp-content/uploads/2015/01/Samoyed-Dog-Wallpapers0.jpg">

<% end %>

<%= link_to t( 'posts.index.index_newpost' ), new_post_path %>

app/views/posts/new.html.erb
<h1><%= t( 'posts.new.page_title' ) %></h1>
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
        <td><%= f.label t( 'posts.new.title' ) %></td>
        <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <td><%= f.label t( 'posts.new.img_url' ) %></td>
      <td><%= f.text_field :img_url%></td>
    </tr>


    <tr>
      <td><%= f.label t( 'posts.new.author' ) %></td>
      <td><%= f.text_field :author %></td>
    </tr>

    <tr>
      <td><%= f.label t( 'posts.new.body' ) %></td>
      <td><%= f.text_area :body %></td>
    </tr>

 </table>


  <p>
    <%= f.submit t( 'posts.new.create_btn' ) %>
  </p>
 
<% end %>

<%= link_to t('.back_btn'), posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <%= image_tag @post.img_url, width: '800px'%>
</p>

<p>
  <%= @post.body %>
</p>
 
<%= link_to t( 'posts.show.back_btn' ) , posts_path %>

app/views/static_pages/about.html.erb
<h1><%= t( 'static_pages.about.about_page_header' ) %></h1>
<p><%= t( 'static_pages.about.about_page_desc' ) %></p>
<p><%= t( 'static_pages.about.about_page_desc2' ) %></p>

<nav >
	<li class="blueberry"><%= image_tag("Blueberry.jpg", width: "300px",height: "300px") %></li>
	<li class="blueberrytext"><%= t( 'static_pages.about.about_page_blueberry' ) %></li>

	<li class="shanghai"><%= image_tag("Shanghai_Cabbage.jpg", width: "300px",height: "300px") %></li>
	<div class="shanghaitext"><%= t( 'static_pages.about.about_page_shanghai' ) %></div>

	<li class="chocolate"><%= image_tag("Chocolate.jpg", width: "300px",height: "300px") %></li>
	<div class="chocolatetext"><%= t( 'static_pages.about.about_page_chocolate' ) %></div>

	<li class="dogfood"><%= image_tag("Dog_Food.jpg", width: "300px",height: "300px") %></li>
	<div class="dogfoodtext"><%= t( 'static_pages.about.about_page_dogfood' ) %></div>
	
</nav>

<p>
		<%= t( 'static_pages.about.about_page_desc3' ) %>
</p>

<script src="application.js"></script>

<script type="text/javascript">
	var blueberry=document.querySelector(".blueberry")
var shanghai=document.querySelector(".shanghai")
var chocolate=document.querySelector(".chocolate")
var dogfood=document.querySelector(".dogfood")

var blueberrytext=document.querySelector(".blueberrytext")
var shanghaitext=document.querySelector(".shanghaitext")
var	chocolatetext=document.querySelector(".chocolatetext")
var dogfoodtext=document.querySelector(".dogfoodtext")

blueberry.addEventListener("click",showblueberrytext)
shanghai.addEventListener("click",showshanghaitext)
chocolate.addEventListener("click",showchocolatetext)
dogfood.addEventListener("click",showdogfoodtext)


function showblueberrytext() {
	blueberrytext.style.display="block"
	shanghaitext.style.display="none"
	chocolatetext.style.display="none"
	dogfoodtext.style.display="none"

}
function showshanghaitext() {
	shanghaitext.style.display="block"
	blueberrytext.style.display="none"
	chocolatetext.style.display="none"
	dogfoodtext.style.display="none"
	
}

function showchocolatetext() {
	chocolatetext.style.display="block"
	blueberrytext.style.display="none"
	shanghaitext.style.display="none"
	dogfoodtext.style.display="none"
}
function showdogfoodtext() {
	dogfoodtext.style.display="block"
	blueberrytext.style.display="none"
	shanghaitext.style.display="none"
	chocolatetext.style.display="none"
}
</script>

app/views/static_pages/blog.html.erb
<h1 class="title"><%= t( 'static_pages.blog.blog_header1' ) %></h1>


<figure>
  <%= image_tag("123.png", width: "800px") %>
</figure>


<p class="credits"><%= t( 'static_pages.blog.blog_credits' ) %><span class="float-right"><%= t( 'static_pages.blog.blog_time' ) %></span></p>
<article>
  <h2><%= t( 'static_pages.blog.blog_header2' ) %></h2>
            
  <p><%= t( 'static_pages.blog.blog_content1' ) %></p>

  <h3><%= t( 'static_pages.blog.blog_header3' ) %></h3>

  <p><%= t( 'static_pages.blog.blog_content4' ) %></p>

</article>

app/views/static_pages/food.html.erb
<h1><%= t( 'static_pages.food.food_page_header' ) %></h1>
<p><%= t( 'static_pages.food.food_page_desc' ) %></p>
<p><%= t( 'static_pages.food.food_page_desc2' ) %></p>

<nav >
	<li class="blueberry"><%= image_tag("Blueberry.jpg", width: "300px",height: "300px") %></li>
	<li class="blueberrytext"><%= t( 'static_pages.food.food_page_blueberry' ) %></li>

	<li class="shanghai"><%= image_tag("Shanghai_Cabbage.jpg", width: "300px",height: "300px") %></li>
	<div class="shanghaitext"><%= t( 'static_pages.food.food_page_shanghai' ) %></div>

	<li class="chocolate"><%= image_tag("Chocolate.jpg", width: "300px",height: "300px") %></li>
	<div class="chocolatetext"><%= t( 'static_pages.food.food_page_chocolate' ) %></div>

	<li class="dogfood"><%= image_tag("Dog_Food.jpg", width: "300px",height: "300px") %></li>
	<div class="dogfoodtext"><%= t( 'static_pages.food.food_page_dogfood' ) %></div>
	
</nav>

<p>
		<%= t( 'static_pages.food.food_page_desc3' ) %>
</p>

<script src="application.js"></script>

<script type="text/javascript">
	var blueberry=document.querySelector(".blueberry")
var shanghai=document.querySelector(".shanghai")
var chocolate=document.querySelector(".chocolate")
var dogfood=document.querySelector(".dogfood")

var blueberrytext=document.querySelector(".blueberrytext")
var shanghaitext=document.querySelector(".shanghaitext")
var	chocolatetext=document.querySelector(".chocolatetext")
var dogfoodtext=document.querySelector(".dogfoodtext")

blueberry.addEventListener("click",showblueberrytext)
shanghai.addEventListener("click",showshanghaitext)
chocolate.addEventListener("click",showchocolatetext)
dogfood.addEventListener("click",showdogfoodtext)


function showblueberrytext() {
	blueberrytext.style.display="block"
	shanghaitext.style.display="none"
	chocolatetext.style.display="none"
	dogfoodtext.style.display="none"

}
function showshanghaitext() {
	shanghaitext.style.display="block"
	blueberrytext.style.display="none"
	chocolatetext.style.display="none"
	dogfoodtext.style.display="none"
	
}

function showchocolatetext() {
	chocolatetext.style.display="block"
	blueberrytext.style.display="none"
	shanghaitext.style.display="none"
	dogfoodtext.style.display="none"
}
function showdogfoodtext() {
	dogfoodtext.style.display="block"
	blueberrytext.style.display="none"
	shanghaitext.style.display="none"
	chocolatetext.style.display="none"
}
</script>

app/views/static_pages/home.html.erb
<div class="floating">
  <h1><%= t('.home_intro') %></h1>
  <p><%= t('.home_intro_2') %></p>
  <p><%= t('.home_intro_3') %></p>
</div>
<aside><%= image_tag I18n.locale.to_s == "bro" ? "monster.png" : "puppy.png" %></aside>